spring:
  devtools:
    livereload:
      enabled: true
  
  mvc:
    hiddenmethod:      filter:        enabled: true
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
      add-mapping: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5000/payheredb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true